project_id = "xrzvbxhnitkdrozmecim"

[functions.luna-memory]
verify_jwt = false

[functions.luna-quiz]
verify_jwt = false

[functions.luna-stt]
verify_jwt = false

[functions.luna-tts]
verify_jwt = false