import type { Archetype, ArchetypeId } from "./types";

export const ARCHETYPES: Record<ArchetypeId, Archetype> = {
  speedster: {
    id: "speedster",
    name: "The Speedster",
    emoji: "//",
    color: "text-neon-cyan",
    borderColor: "border-neon-cyan/40",
    description: "Fast, pressured gameplay. Less time but higher damage when answering quickly.",
    passive: "Low time · High damage · Streak king",
    stats: { health: 1, time: 1, damage: 3, multiplier: 3, difficulty: 3 },
  },
  tank: {
    id: "tank",
    name: "The Tank",
    emoji: "[#]",
    color: "text-tier-silver",
    borderColor: "border-tier-silver/40",
    description: "Heavy, durable, easy questions. Tons of HP but low damage output.",
    passive: "Max HP · Easy Qs · Low DMG",
    stats: { health: 4, time: 3, damage: 1, multiplier: 2, difficulty: 1 },
  },
  chud: {
    id: "chud",
    name: "The Chud",
    emoji: "x_x",
    color: "text-tier-champion",
    borderColor: "border-tier-champion/40",
    description: "Glass cannon. Ultra-high damage with hard questions and almost no HP.",
    passive: "Ultra DMG · Hard Qs · Glass cannon",
    stats: { health: 0, time: 1, damage: 4, multiplier: 1, difficulty: 4 },
  },
  gambler: {
    id: "gambler",
    name: "The Gambler",
    emoji: "[?]",
    color: "text-tier-gold",
    borderColor: "border-tier-gold/40",
    description: "All stats randomized each turn. High risk, high reward gameplay.",
    passive: "Random stats · Chaos mode",
    stats: { health: 2, time: 2, damage: 2, multiplier: 2, difficulty: 2 },
  },
  healer: {
    id: "healer",
    name: "The Healer",
    emoji: "(+)",
    color: "text-neon-pink",
    borderColor: "border-neon-pink/40",
    description: "Sustain-focused with high HP, easy questions, but low damage.",
    passive: "Heal on defend · Sustain king",
    stats: { health: 3, time: 3, damage: 1, multiplier: 2, difficulty: 1 },
  },
  fulcrum: {
    id: "fulcrum",
    name: "The Fulcrum",
    emoji: "<=>",
    color: "text-neon-purple",
    borderColor: "border-neon-purple/40",
    description: "Balanced all-rounder with the highest multiplier. Rewards consistency.",
    passive: "Max multiplier · Combo every 2 hits",
    stats: { health: 2, time: 2, damage: 2, multiplier: 4, difficulty: 2 },
  },
  accelerator: {
    id: "accelerator",
    name: "The Accelerator",
    emoji: ">>",
    color: "text-tier-platinum",
    borderColor: "border-tier-platinum/40",
    description: "Scaling power over time. Damage increases every turn. Harder questions.",
    passive: "DMG scales · Hard Qs · Big finish",
    stats: { health: 2, time: 2, damage: 1, multiplier: 3, difficulty: 3 },
  },
  god: {
    id: "god",
    name: "The God",
    emoji: "[*]",
    color: "text-tier-god",
    borderColor: "border-tier-god/40",
    description: "Endgame archetype. Max stats across the board with hardest questions.",
    passive: "All stats maxed · Ultimate form",
    stats: { health: 4, time: 4, damage: 4, multiplier: 4, difficulty: 4 },
  },
};
