import type { Archetype, ArchetypeId } from "./types";

export const ARCHETYPES: Record<ArchetypeId, Archetype> = {
  speedster: {
    id: "speedster",
    name: "The Speedster",
    emoji: "⚡",
    color: "text-neon-cyan",
    borderColor: "border-neon-cyan/40",
    description: "Fast, agile, combo-focused. Bonus damage scales with time remaining.",
    passive: "Speed DMG bonus · Fast = lethal",
    stats: { attack: 2, defense: 1, speed: 4, combo: 3 },
  },
  tank: {
    id: "tank",
    name: "The Tank",
    emoji: "🛡️",
    color: "text-tier-silver",
    borderColor: "border-tier-silver/40",
    description: "Heavy, durable, slow hitters. Wrong answers deal only 50% self-damage.",
    passive: "Self-DMG −50% · Base ATK −30%",
    stats: { attack: 1, defense: 4, speed: 1, combo: 2 },
  },
  chud: {
    id: "chud",
    name: "The Chud",
    emoji: "😵",
    color: "text-tier-champion",
    borderColor: "border-tier-champion/40",
    description: "Chaotic, reckless, glass cannon. Ultra-high damage but extremely fragile.",
    passive: "Ultra DMG · Glass cannon",
    stats: { attack: 4, defense: 0, speed: 3, combo: 1 },
  },
  gambler: {
    id: "gambler",
    name: "The Gambler",
    emoji: "🎰",
    color: "text-tier-gold",
    borderColor: "border-tier-gold/40",
    description: "Luck-based and unpredictable. All stats are randomized each turn.",
    passive: "Random stats · High risk/reward",
    stats: { attack: 2, defense: 2, speed: 2, combo: 2 },
  },
  healer: {
    id: "healer",
    name: "The Healer",
    emoji: "✨",
    color: "text-neon-pink",
    borderColor: "border-neon-pink/40",
    description: "Support-focused with sustain. Can heal instead of attacking.",
    passive: "Heal on defend · Sustain king",
    stats: { attack: 1, defense: 3, speed: 2, combo: 2 },
  },
  fulcrum: {
    id: "fulcrum",
    name: "The Fulcrum",
    emoji: "⚖️",
    color: "text-neon-purple",
    borderColor: "border-neon-purple/40",
    description: "Balanced, consistent all-rounder. Combo multiplier triggers every 2 hits.",
    passive: "Combo every 2 hits · Steady power",
    stats: { attack: 2, defense: 2, speed: 2, combo: 4 },
  },
  accelerator: {
    id: "accelerator",
    name: "The Accelerator",
    emoji: "⏩",
    color: "text-tier-platinum",
    borderColor: "border-tier-platinum/40",
    description: "Scaling power over time. Damage increases every turn.",
    passive: "DMG scales · Slow start, big finish",
    stats: { attack: 1, defense: 2, speed: 2, combo: 3 },
  },
  god: {
    id: "god",
    name: "The God",
    emoji: "👑",
    color: "text-tier-god",
    borderColor: "border-tier-god/40",
    description: "Endgame archetype with overwhelming power across all stats.",
    passive: "All stats maxed · Ultimate form",
    stats: { attack: 4, defense: 4, speed: 4, combo: 4 },
  },
};
