/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CertifiedRouteImport } from './routes/certified'
import { Route as BuildCourseRouteImport } from './routes/build-course'
import { Route as AdaptiveTestsRouteImport } from './routes/adaptive-tests'
import { Route as IndexRouteImport } from './routes/index'

const CertifiedRoute = CertifiedRouteImport.update({
  id: '/certified',
  path: '/certified',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCourseRoute = BuildCourseRouteImport.update({
  id: '/build-course',
  path: '/build-course',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptiveTestsRoute = AdaptiveTestsRouteImport.update({
  id: '/adaptive-tests',
  path: '/adaptive-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adaptive-tests': typeof AdaptiveTestsRoute
  '/build-course': typeof BuildCourseRoute
  '/certified': typeof CertifiedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adaptive-tests': typeof AdaptiveTestsRoute
  '/build-course': typeof BuildCourseRoute
  '/certified': typeof CertifiedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adaptive-tests': typeof AdaptiveTestsRoute
  '/build-course': typeof BuildCourseRoute
  '/certified': typeof CertifiedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adaptive-tests' | '/build-course' | '/certified'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adaptive-tests' | '/build-course' | '/certified'
  id: '__root__' | '/' | '/adaptive-tests' | '/build-course' | '/certified'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptiveTestsRoute: typeof AdaptiveTestsRoute
  BuildCourseRoute: typeof BuildCourseRoute
  CertifiedRoute: typeof CertifiedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/certified': {
      id: '/certified'
      path: '/certified'
      fullPath: '/certified'
      preLoaderRoute: typeof CertifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-course': {
      id: '/build-course'
      path: '/build-course'
      fullPath: '/build-course'
      preLoaderRoute: typeof BuildCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive-tests': {
      id: '/adaptive-tests'
      path: '/adaptive-tests'
      fullPath: '/adaptive-tests'
      preLoaderRoute: typeof AdaptiveTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptiveTestsRoute: AdaptiveTestsRoute,
  BuildCourseRoute: BuildCourseRoute,
  CertifiedRoute: CertifiedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
