/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated.progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedLunaRouteImport } from './routes/_authenticated.luna'
import { Route as AuthenticatedForumRouteImport } from './routes/_authenticated.forum'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated.collection'
import { Route as AuthenticatedCertifiedRouteImport } from './routes/_authenticated.certified'
import { Route as AuthenticatedBuildCourseRouteImport } from './routes/_authenticated.build-course'
import { Route as AuthenticatedBattlesRouteImport } from './routes/_authenticated.battles'
import { Route as AuthenticatedAdaptiveTestsRouteImport } from './routes/_authenticated.adaptive-tests'
import { Route as AuthenticatedForumThreadIdRouteImport } from './routes/_authenticated.forum.$threadId'
import { Route as AuthenticatedCertifiedSlugRouteImport } from './routes/_authenticated.certified.$slug'
import { Route as AuthenticatedAdminForumRouteImport } from './routes/_authenticated.admin.forum'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLunaRoute = AuthenticatedLunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForumRoute = AuthenticatedForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertifiedRoute = AuthenticatedCertifiedRouteImport.update({
  id: '/certified',
  path: '/certified',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuildCourseRoute =
  AuthenticatedBuildCourseRouteImport.update({
    id: '/build-course',
    path: '/build-course',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBattlesRoute = AuthenticatedBattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdaptiveTestsRoute =
  AuthenticatedAdaptiveTestsRouteImport.update({
    id: '/adaptive-tests',
    path: '/adaptive-tests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedForumThreadIdRoute =
  AuthenticatedForumThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedForumRoute,
  } as any)
const AuthenticatedCertifiedSlugRoute =
  AuthenticatedCertifiedSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCertifiedRoute,
  } as any)
const AuthenticatedAdminForumRoute = AuthenticatedAdminForumRouteImport.update({
  id: '/admin/forum',
  path: '/admin/forum',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/adaptive-tests': typeof AuthenticatedAdaptiveTestsRoute
  '/battles': typeof AuthenticatedBattlesRoute
  '/build-course': typeof AuthenticatedBuildCourseRoute
  '/certified': typeof AuthenticatedCertifiedRouteWithChildren
  '/collection': typeof AuthenticatedCollectionRoute
  '/forum': typeof AuthenticatedForumRouteWithChildren
  '/luna': typeof AuthenticatedLunaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/certified/$slug': typeof AuthenticatedCertifiedSlugRoute
  '/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/adaptive-tests': typeof AuthenticatedAdaptiveTestsRoute
  '/battles': typeof AuthenticatedBattlesRoute
  '/build-course': typeof AuthenticatedBuildCourseRoute
  '/certified': typeof AuthenticatedCertifiedRouteWithChildren
  '/collection': typeof AuthenticatedCollectionRoute
  '/forum': typeof AuthenticatedForumRouteWithChildren
  '/luna': typeof AuthenticatedLunaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/certified/$slug': typeof AuthenticatedCertifiedSlugRoute
  '/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/adaptive-tests': typeof AuthenticatedAdaptiveTestsRoute
  '/_authenticated/battles': typeof AuthenticatedBattlesRoute
  '/_authenticated/build-course': typeof AuthenticatedBuildCourseRoute
  '/_authenticated/certified': typeof AuthenticatedCertifiedRouteWithChildren
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/forum': typeof AuthenticatedForumRouteWithChildren
  '/_authenticated/luna': typeof AuthenticatedLunaRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/admin/forum': typeof AuthenticatedAdminForumRoute
  '/_authenticated/certified/$slug': typeof AuthenticatedCertifiedSlugRoute
  '/_authenticated/forum/$threadId': typeof AuthenticatedForumThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/certified'
    | '/collection'
    | '/forum'
    | '/luna'
    | '/profile'
    | '/progress'
    | '/u/$username'
    | '/admin/forum'
    | '/certified/$slug'
    | '/forum/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/certified'
    | '/collection'
    | '/forum'
    | '/luna'
    | '/profile'
    | '/progress'
    | '/u/$username'
    | '/admin/forum'
    | '/certified/$slug'
    | '/forum/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/adaptive-tests'
    | '/_authenticated/battles'
    | '/_authenticated/build-course'
    | '/_authenticated/certified'
    | '/_authenticated/collection'
    | '/_authenticated/forum'
    | '/_authenticated/luna'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/u/$username'
    | '/_authenticated/admin/forum'
    | '/_authenticated/certified/$slug'
    | '/_authenticated/forum/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/luna': {
      id: '/_authenticated/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof AuthenticatedLunaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forum': {
      id: '/_authenticated/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof AuthenticatedForumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certified': {
      id: '/_authenticated/certified'
      path: '/certified'
      fullPath: '/certified'
      preLoaderRoute: typeof AuthenticatedCertifiedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/build-course': {
      id: '/_authenticated/build-course'
      path: '/build-course'
      fullPath: '/build-course'
      preLoaderRoute: typeof AuthenticatedBuildCourseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/battles': {
      id: '/_authenticated/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof AuthenticatedBattlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adaptive-tests': {
      id: '/_authenticated/adaptive-tests'
      path: '/adaptive-tests'
      fullPath: '/adaptive-tests'
      preLoaderRoute: typeof AuthenticatedAdaptiveTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forum/$threadId': {
      id: '/_authenticated/forum/$threadId'
      path: '/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof AuthenticatedForumThreadIdRouteImport
      parentRoute: typeof AuthenticatedForumRoute
    }
    '/_authenticated/certified/$slug': {
      id: '/_authenticated/certified/$slug'
      path: '/$slug'
      fullPath: '/certified/$slug'
      preLoaderRoute: typeof AuthenticatedCertifiedSlugRouteImport
      parentRoute: typeof AuthenticatedCertifiedRoute
    }
    '/_authenticated/admin/forum': {
      id: '/_authenticated/admin/forum'
      path: '/admin/forum'
      fullPath: '/admin/forum'
      preLoaderRoute: typeof AuthenticatedAdminForumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedCertifiedRouteChildren {
  AuthenticatedCertifiedSlugRoute: typeof AuthenticatedCertifiedSlugRoute
}

const AuthenticatedCertifiedRouteChildren: AuthenticatedCertifiedRouteChildren =
  {
    AuthenticatedCertifiedSlugRoute: AuthenticatedCertifiedSlugRoute,
  }

const AuthenticatedCertifiedRouteWithChildren =
  AuthenticatedCertifiedRoute._addFileChildren(
    AuthenticatedCertifiedRouteChildren,
  )

interface AuthenticatedForumRouteChildren {
  AuthenticatedForumThreadIdRoute: typeof AuthenticatedForumThreadIdRoute
}

const AuthenticatedForumRouteChildren: AuthenticatedForumRouteChildren = {
  AuthenticatedForumThreadIdRoute: AuthenticatedForumThreadIdRoute,
}

const AuthenticatedForumRouteWithChildren =
  AuthenticatedForumRoute._addFileChildren(AuthenticatedForumRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdaptiveTestsRoute: typeof AuthenticatedAdaptiveTestsRoute
  AuthenticatedBattlesRoute: typeof AuthenticatedBattlesRoute
  AuthenticatedBuildCourseRoute: typeof AuthenticatedBuildCourseRoute
  AuthenticatedCertifiedRoute: typeof AuthenticatedCertifiedRouteWithChildren
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedForumRoute: typeof AuthenticatedForumRouteWithChildren
  AuthenticatedLunaRoute: typeof AuthenticatedLunaRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedAdminForumRoute: typeof AuthenticatedAdminForumRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdaptiveTestsRoute: AuthenticatedAdaptiveTestsRoute,
  AuthenticatedBattlesRoute: AuthenticatedBattlesRoute,
  AuthenticatedBuildCourseRoute: AuthenticatedBuildCourseRoute,
  AuthenticatedCertifiedRoute: AuthenticatedCertifiedRouteWithChildren,
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedForumRoute: AuthenticatedForumRouteWithChildren,
  AuthenticatedLunaRoute: AuthenticatedLunaRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedAdminForumRoute: AuthenticatedAdminForumRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
