/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PersonalizedRouteImport } from './routes/personalized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CertifiedRouteImport } from './routes/certified'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated.progress'
import { Route as AuthenticatedLunaRouteImport } from './routes/_authenticated.luna'
import { Route as AuthenticatedForumRouteImport } from './routes/_authenticated.forum'
import { Route as AuthenticatedBuildCourseRouteImport } from './routes/_authenticated.build-course'
import { Route as AuthenticatedBattlesRouteImport } from './routes/_authenticated.battles'
import { Route as AuthenticatedAdaptiveTestsRouteImport } from './routes/_authenticated.adaptive-tests'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizedRoute = PersonalizedRouteImport.update({
  id: '/personalized',
  path: '/personalized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifiedRoute = CertifiedRouteImport.update({
  id: '/certified',
  path: '/certified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLunaRoute = AuthenticatedLunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForumRoute = AuthenticatedForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuildCourseRoute =
  AuthenticatedBuildCourseRouteImport.update({
    id: '/build-course',
    path: '/build-course',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBattlesRoute = AuthenticatedBattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdaptiveTestsRoute =
  AuthenticatedAdaptiveTestsRouteImport.update({
    id: '/adaptive-tests',
    path: '/adaptive-tests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certified': typeof CertifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/personalized': typeof PersonalizedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/adaptive-tests': typeof AuthenticatedAdaptiveTestsRoute
  '/battles': typeof AuthenticatedBattlesRoute
  '/build-course': typeof AuthenticatedBuildCourseRoute
  '/forum': typeof AuthenticatedForumRoute
  '/luna': typeof AuthenticatedLunaRoute
  '/progress': typeof AuthenticatedProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certified': typeof CertifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/personalized': typeof PersonalizedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/adaptive-tests': typeof AuthenticatedAdaptiveTestsRoute
  '/battles': typeof AuthenticatedBattlesRoute
  '/build-course': typeof AuthenticatedBuildCourseRoute
  '/forum': typeof AuthenticatedForumRoute
  '/luna': typeof AuthenticatedLunaRoute
  '/progress': typeof AuthenticatedProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/certified': typeof CertifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/personalized': typeof PersonalizedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/adaptive-tests': typeof AuthenticatedAdaptiveTestsRoute
  '/_authenticated/battles': typeof AuthenticatedBattlesRoute
  '/_authenticated/build-course': typeof AuthenticatedBuildCourseRoute
  '/_authenticated/forum': typeof AuthenticatedForumRoute
  '/_authenticated/luna': typeof AuthenticatedLunaRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certified'
    | '/forgot-password'
    | '/login'
    | '/personalized'
    | '/reset-password'
    | '/signup'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/forum'
    | '/luna'
    | '/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certified'
    | '/forgot-password'
    | '/login'
    | '/personalized'
    | '/reset-password'
    | '/signup'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/forum'
    | '/luna'
    | '/progress'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/certified'
    | '/forgot-password'
    | '/login'
    | '/personalized'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/adaptive-tests'
    | '/_authenticated/battles'
    | '/_authenticated/build-course'
    | '/_authenticated/forum'
    | '/_authenticated/luna'
    | '/_authenticated/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CertifiedRoute: typeof CertifiedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PersonalizedRoute: typeof PersonalizedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalized': {
      id: '/personalized'
      path: '/personalized'
      fullPath: '/personalized'
      preLoaderRoute: typeof PersonalizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certified': {
      id: '/certified'
      path: '/certified'
      fullPath: '/certified'
      preLoaderRoute: typeof CertifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/luna': {
      id: '/_authenticated/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof AuthenticatedLunaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forum': {
      id: '/_authenticated/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof AuthenticatedForumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/build-course': {
      id: '/_authenticated/build-course'
      path: '/build-course'
      fullPath: '/build-course'
      preLoaderRoute: typeof AuthenticatedBuildCourseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/battles': {
      id: '/_authenticated/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof AuthenticatedBattlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adaptive-tests': {
      id: '/_authenticated/adaptive-tests'
      path: '/adaptive-tests'
      fullPath: '/adaptive-tests'
      preLoaderRoute: typeof AuthenticatedAdaptiveTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdaptiveTestsRoute: typeof AuthenticatedAdaptiveTestsRoute
  AuthenticatedBattlesRoute: typeof AuthenticatedBattlesRoute
  AuthenticatedBuildCourseRoute: typeof AuthenticatedBuildCourseRoute
  AuthenticatedForumRoute: typeof AuthenticatedForumRoute
  AuthenticatedLunaRoute: typeof AuthenticatedLunaRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdaptiveTestsRoute: AuthenticatedAdaptiveTestsRoute,
  AuthenticatedBattlesRoute: AuthenticatedBattlesRoute,
  AuthenticatedBuildCourseRoute: AuthenticatedBuildCourseRoute,
  AuthenticatedForumRoute: AuthenticatedForumRoute,
  AuthenticatedLunaRoute: AuthenticatedLunaRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CertifiedRoute: CertifiedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PersonalizedRoute: PersonalizedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
